#!/bin/bash

ID=$(id -u)

if [ $ID -ne 0 ]
  then
      echo "Error: Please as a  root user "
      exit 1
else
      echo "You are root user"
fi

VALIDATE(){

  if [ $? -ne 0 ]
    then 
      echo "Installation  failed!!"
      exit 1
  else
      echo "Installtion succesfull!"
   fi
}



yum install mysql -y
VALIDATE 


yum install git -y
VALIDATE
