#!/bin/bash

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

TIMESTAMP=$(date +%F-%M-%H-%S)
LOGFILE="/tmp/$0-TIMESTAMP.log"

echo -e " $Y The script name: $G $0 $N"
echo -e "script started at $TIMESTAMP" &>> $LOGFILE
ID=$(id -u)

if [ $ID -ne 0 ]
  then
      echo -e "$R ERROR: root user access denied!! $N "
      exit 1
else
      echo -e "You are $Y Root $N user"
fi

VALIDATE(){
  
  if [ $1 -ne 0 ]
    then 
        echo "$2 ....failed!!"
  else
        echo "$2 .....Success!!"
  fi
}

yum install mysql -y &>> $LOGFILE

VALIDATE $? "Insatalling MYSQL"

yum install git -y &>> $LOGFILE

VALIDATE $? "Insatlling GIT"



