#!/bin/bash

ID=$(id -u)

R="\e[31m"
G="\e[32m"
N="\e[0m"

echo -e " $R script name:$G $0 $N"


TIMESTAMP=$(date +%F-%H-%M-%S)
LOGFILE="/tmp/$0-$TIMESTAMP.log"

if [ $ID -ne 0 ]
  then
      echo -e "Error: $R Please Login as a  root user "
      exit 1
else
      echo -e "You are $G root $N user"
fi

VALIDATE(){

  if [ $1 -ne 0 ]
    then 
      echo -e  "$2 .... $R failed!! $N "
      exit 1
  else
      echo -e " $2 ....$G succesfull! $N "
   fi
}



yum install mysql -y &>> $LOGFILE

VALIDATE $? "Installing Mysql"


yum install git -y &>> $LOGFILE

VALIDATE $? "Installing Git"
